### ISSUE TITLE
SOQL : lstOpportunity = [SELECT Account.Group__c,Account.Id,Account.Ts_Id__c,Type FROM Opportunity where Id IN :mapOfOpp.keySet()]; In this example, " :mapOfOpp.keySet()" is not getting parse

### ISSUE THREAD

**Issue by sachinshinde729** [fundacionjala/enforce-sonarqube-plugin#118]
I am trying to use this plugin to build few rules. But I have found few issue related to parsing SOQL.

Example -->
SOQL : lstOpportunity = [SELECT Account.Group__c,Account.Id,Account.Ts_Id__c,Type FROM Opportunity where Id IN :mapOfOpp.keySet()];
In this example, " :mapOfOpp.keySet()" is not getting parsed.

The above is just an example, I want to discuss with you few of these issue.
If possible, we will like to have a call with you over skype.

This is an high priority issue for us, as this has been escalated by client.

Taging @pagwekar

**Comment by goldmane** [comment]
@sachinshinde729 - see #116 comments as the proposed fix in #119 should address this as well
