### ISSUE TITLE
Issue with SLF4J

### ISSUE THREAD

**Issue by rahulAppirio** [fundacionjala/enforce-sonarqube-plugin#128]
Hi Team,

I am getting following error during performing Maven Install command:

> LF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

I am using JDK 1.8, Maven 3.5.2 for setup this. I have downloaded zip folder locally and imported in eclipse Neon using Maven Import.

While doing investigation, I have found that, Maven dependency folder across all projects:
> Apex-check
> apex-plugin
> apex-toolkit
> apex-squid
have following version of SLF4J and related bindings:
1. jcl-over-slf4j(1.7.5, 1.5.6 ...)
2. slf4j-jdk14 (1.5.6)
3. slf4j-api (1.7.5, 1.5.6 ...)
4. log4j-slf4j (1.7.5, 1.5.6 ...)

When we try to run the code we got the above exception. Any help on this direction will be appreciated.

Thanks,
Rahul

**Comment by abd3** [comment]
#129 resolves this
