### ISSUE TITLE
Test methods should be defined using the testMethod keyword.

### ISSUE THREAD

**Issue by kevinTveizaga** [fundacionjala/enforce-sonarqube-plugin#42]
To define an Apex method as a 'test method', simply define the method as static and add the keyword testMethod. A test method can be defined in any Apex class. A test method can not be defined in an Apex trigger. (Note: Testmethods cannot be called outside of a test context.)
## **Noncompliant Code Example**

public class myClass {
     static void myTest(){} // missing testMethod keyword.
}
### Defining a Test Method using the testMethod keyword

public class myClass {
&nbsp;&nbsp;&nbsp;&nbsp;static testMethod void myTest() {
&nbsp;&nbsp;&nbsp;&nbsp;// Add test method logic using System.assert(), System.assertEquals()
&nbsp;&nbsp;&nbsp;&nbsp;// and System.assertNotEquals() here.
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;testMethod void myTest() {
&nbsp;&nbsp;&nbsp;&nbsp;}
}

**Comment by JimmyRojas** [comment]
Noncompliant Code Example

public class myClass {
testMethod void myTest() {} //missing static keyword
static void myTest(){} // missing testMethod keyword.
}

static void myTest(){} // missing testMethod keyword.

it is possible a test class contains static methods as normal methods

**Comment by VarS311** [comment]
@JimmyRojas You're right. I think it should be a little more specific, for example the check should recognize the issue when the method name has the word "test" in it but it's not declared as a "testMethod". And we should create another issue about testMethods being declared only inside test classes; I'll take care of that right away.
